# Generated by Django 6.0 on 2025-12-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='room_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
